import type { TripPlan } from "@/types";

export const sampleTripPlan: TripPlan = {
  origin: "San Francisco, CA",
  destination: "Los Angeles, CA",
  waypoints: ["Monterey", "Big Sur", "Santa Barbara"],
  route: {
    distanceKm: 615,
    durationHours: 9.5,
    polyline: [
      [37.7749, -122.4194],
      [36.6002, -121.8947],
      [36.2456, -121.7835],
      [35.3677, -120.8499],
      [34.4208, -119.6982],
      [34.0522, -118.2437],
    ],
    stops: ["Monterey", "Big Sur", "Santa Barbara"],
  },
  weather: [
    {
      date: "2025-06-01",
      day_name: "Monday",
      location: "Monterey",
      temp_min_celsius: 14,
      temp_max_celsius: 20,
      temp_feels_like: 18,
      humidity_percent: 72,
      condition: "Cloudy with light coastal breeze",
      weather_icon: "🌤️",
      wind_speed_kmh: 14.8,
      rain_chance_percent: 10,
      alert: null,
    },
    {
      date: "2025-06-03",
      day_name: "Wednesday",
      location: "Santa Barbara",
      temp_min_celsius: 18,
      temp_max_celsius: 27,
      temp_feels_like: 24,
      humidity_percent: 58,
      condition: "Bright and warm",
      weather_icon: "☀️",
      wind_speed_kmh: 9.6,
      rain_chance_percent: 0,
      alert: null,
    },
  ],
  budget: {
    fuel: 145,
    lodging: 420,
    food: 180,
    activities: 120,
    total: 865,
  },
  recommendations: [
    {
      title: "Big Sur scenic stop",
      description: "Plan a sunset pause here to avoid driving the coastal curves after dark.",
      category: "Scenic",
      priority: 1,
    },
    {
      title: "Refuel near Paso Robles",
      description: "Prices tend to be friendlier inland, so top off before the final stretch.",
      category: "Budget",
      priority: 2,
    },
    {
      title: "Reserve lodging in advance",
      description: "Coastal stays fill up early on weekends, especially in Santa Barbara.",
      category: "Logistics",
      priority: 3,
    },
  ],
  chat: [
    {
      id: "1",
      role: "assistant",
      content: "I’ve mapped a scenic coastal route with three recommended stops and one overnight break.",
      timestamp: new Date().toISOString(),
    },
    {
      id: "2",
      role: "user",
      content: "Can we keep fuel costs under $150?",
      timestamp: new Date().toISOString(),
    },
    {
      id: "3",
      role: "assistant",
      content: "Yes. Keep the tank topped up near inland towns and avoid premium stations near tourist spots.",
      timestamp: new Date().toISOString(),
    },
  ],
};
